Repository plugwise/python-plugwise, pull requests merged in 2020-10, with the labels that each got.

#5 Add notifications like 112 in Plugwise-Smile
  tests/test_smile.py
Labels: enhancement

#7 Merging changelogs
  CHANGELOG.md
Labels: documentation

#8 Devsetup
  .coveragerc
  .travis.yml
  README.md
  requirements.txt
  scripts/setup.sh
  scripts/setup_test.sh
  scripts/tests_and_coverage.sh
  setup.py
  tests/README.md
Labels: documentation, enhancement

#4 Add documenation on setup
  tests/INIT.md
Labels: documentation, enhancement

#6 Merge the stick-files
  plugwise/__init__.py
  plugwise/connections/__init__.py
  plugwise/connections/connection.py
  plugwise/connections/serial.py
  plugwise/connections/socket.py
  plugwise/constants.py
  plugwise/exceptions.py
  plugwise/message.py
  plugwise/messages/__init__.py
  plugwise/messages/requests.py
  plugwise/messages/responses.py
  plugwise/node.py
  plugwise/nodes/__init__.py
  plugwise/nodes/circle.py
  plugwise/nodes/circle_plus.py
  plugwise/nodes/scan.py
  plugwise/nodes/sed.py
  plugwise/nodes/sense.py
  plugwise/nodes/stealth.py
  plugwise/nodes/switch.py
  plugwise/parser.py
  plugwise/stick.py
  plugwise/util.py
  setup.py
Labels: enhancement

#10 Update badges
  README.md
Labels: documentation

#11 Update badges #2
  README.md
Labels: documentation

#12 Update badges #3
  README.md
Labels: bug, documentation

#13 Fix installing within HA core
  plugwise/__init__.py
  setup.cfg
Labels: bug

#14 Rewording and remove outdated statements, include license history
  README.md
Labels: documentation

#24 Improve code styling-quality and migrate to GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/merge.yml
  .github/workflows/publish-to-test-pypi.yml
  .github/workflows/verify.yml
  .travis.yml.disabled
  CHANGELOG.md
  README.md
  SECURITY.md
  plugwise/__init__.py
  plugwise/connections/connection.py
  plugwise/connections/serial.py
  plugwise/connections/socket.py
  plugwise/constants.py
  plugwise/message.py
  plugwise/messages/requests.py
  plugwise/messages/responses.py
  plugwise/node.py
  plugwise/nodes/circle.py
  plugwise/nodes/circle_plus.py
  plugwise/nodes/scan.py
  plugwise/nodes/sed.py
  plugwise/nodes/sense.py
  plugwise/nodes/switch.py
  plugwise/parser.py
  plugwise/smile.py
  plugwise/stick.py
  plugwise/util.py
  setup.py
  tests/INIT.md
  tests/test_smile.py
Labels: enhancement

#30 Linter run on top of qualtiy-branch
  .bandit
  .coveragerc
  .github/workflows/verify.yml
  CHANGELOG.md
  plugwise/__init__.py
  plugwise/connections/__init__.py
  plugwise/connections/connection.py
  plugwise/connections/serial.py
  plugwise/connections/socket.py
  plugwise/exceptions.py
  plugwise/message.py
  plugwise/messages/__init__.py
  plugwise/messages/requests.py
  plugwise/messages/responses.py
  plugwise/node.py
  plugwise/nodes/__init__.py
  plugwise/nodes/circle.py
  plugwise/nodes/circle_plus.py
  plugwise/nodes/scan.py
  plugwise/nodes/sed.py
  plugwise/nodes/sense.py
  plugwise/nodes/stealth.py
  plugwise/nodes/switch.py
  plugwise/parser.py
  plugwise/smile.py
  plugwise/stick.py
  plugwise/util.py
  pylintrc
  scripts/pre-commit.sh
  scripts/tests_and_coverage.sh
  setup.py
  tests/bandit.yaml
  tests/test_smile.py
Labels: enhancement
