Repository plugwise/python-plugwise, pull requests merged in 2022-12, with the labels that each got.

#250 Improve dependency checking
  .github/workflows/verify.yml
  .gitignore
  package_constraints.txt
  requirements_commit.txt
  requirements_test.txt
  scripts/dependencies_check.sh
  tests/test_smile.py
Labels: enhancement, dependencies, github_actions

#255 Install pre-commit.ci
  .flake8
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/verify.yml
  .pre-commit-config.yaml
  README.md
  setup.cfg
  tests/test_smile.py
Labels: enhancement, dependencies

#253 Pyproject.toml PEP-621 including versioning & cleanup of separate config files
  .coveragerc
  .github/workflows/merge.yml
  .github/workflows/verify.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  plugwise/__init__.py
  pyproject.toml
  pytest.ini
  scripts/setup.sh
  scripts/setup_test.sh
  setup.cfg
  setup.py
  tests/INIT.md
Labels: documentation, enhancement, python

#256 3.10 as string
  .github/workflows/merge.yml
Labels: bug, enhancement
