Repository plugwise/python-plugwise, pull requests merged in 2023-12, with the labels that each got.

#478 Cache bump
  .github/workflows/verify.yml
Labels: bug

#479 Try combining both actions to v4
  .github/workflows/verify.yml
Labels: github_actions

#484 Py bump and ruff over black/isort
  .github/workflows/merge.yml
  .github/workflows/verify.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  plugwise/__init__.py
  plugwise/helper.py
  plugwise/util.py
  pyproject.toml
  requirements_commit.txt
  scripts/tests_and_coverage.sh
  tests/test_smile.py
Labels: enhancement, dependencies, quality

#483 Split testing - initial split
  CHANGELOG.md
  tests/__init__.py
  tests/data/adam/adam_heatpump_cooling.json
  tests/data/adam/adam_jip.json
  tests/data/adam/adam_multiple_devices_per_zone.json
  tests/data/adam/adam_onoff_cooling_fake_firmware.json
  tests/data/adam/adam_plus_anna.json
  tests/data/adam/adam_plus_anna_new.json
  tests/data/adam/adam_plus_anna_new_UPDATED_DATA.json
  tests/data/adam/adam_zone_per_device.json
  tests/data/anna/anna_elga_2.json
  tests/data/anna/anna_elga_2_cooling.json
  tests/data/anna/anna_elga_2_schedule_off.json
  tests/data/anna/anna_heatpump_cooling.json
  tests/data/anna/anna_heatpump_cooling_fake_firmware.json
  tests/data/anna/anna_heatpump_heating.json
  tests/data/anna/anna_heatpump_heating_UPDATED_DATA.json
  tests/data/anna/anna_loria_cooling_active.json
  tests/data/anna/anna_loria_driessens.json
  tests/data/anna/anna_loria_heating_idle.json
  tests/data/anna/anna_v4.json
  tests/data/anna/anna_v4_UPDATED_DATA.json
  tests/data/anna/anna_v4_dhw.json
  tests/data/anna/anna_without_boiler_fw441.json
  tests/data/anna/legacy_anna.json
  tests/data/anna/legacy_anna_2.json
  tests/data/p1/p1v4.json
  tests/data/p1/p1v4_442_single.json
  tests/data/p1/p1v4_442_single_UPDATED_DATA.json
  tests/data/p1/p1v4_442_triple.json
  tests/data/p1/smile_p1_v2.json
  tests/data/p1/smile_p1_v2_2.json
  tests/data/p1/smile_p1_v2_2_UPDATED_DATA.json
  tests/data/stretch/stretch_v23.json
  tests/data/stretch/stretch_v27_no_domain.json
  tests/data/stretch/stretch_v31.json
  tests/data/stretch/stretch_v31_UPDATED_DATA.json
  tests/test_adam.py
  tests/test_anna.py
  tests/test_generic.py
  tests/test_init.py
  tests/test_p1.py
  tests/test_smile.py
  tests/test_stretch.py
Labels: enhancement, quality

#485 Quality improvements (through sonar cloud)
  CHANGELOG.md
  plugwise/__init__.py
  plugwise/constants.py
  plugwise/helper.py
  plugwise/util.py
Labels: quality

#487 Fix for beta issue 574
  CHANGELOG.md
  fixtures/anna_elga_no_cooling/all_data.json
  fixtures/anna_elga_no_cooling/device_list.json
  fixtures/anna_elga_no_cooling/notifications.json
  plugwise/constants.py
  plugwise/helper.py
  pyproject.toml
  tests/data/anna/anna_elga_no_cooling.json
  tests/test_anna.py
  userdata/anna_elga_no_cooling/core.appliances.xml
  userdata/anna_elga_no_cooling/core.direct_objects.xml
  userdata/anna_elga_no_cooling/core.domain_objects.xml
  userdata/anna_elga_no_cooling/core.locations.xml
  userdata/anna_elga_no_cooling/core.modules.xml
Labels: bug, enhancement
