Repository plugwise/python-plugwise, pull requests merged in 2023-06, with the labels that each got.

#324 Loria-related fixes (as recently mentioned in plugwise-beta issue #301)
  CHANGELOG.md
  fixtures/adam_heatpump_cooling/all_data.json
  fixtures/adam_onoff_cooling_fake_firmware/all_data.json
  fixtures/anna_elga_2_cooling/all_data.json
  fixtures/anna_loria_cooling_active/all_data.json
  fixtures/anna_loria_heating_idle/all_data.json
  plugwise/__init__.py
  plugwise/helper.py
  pyproject.toml
  tests/test_smile.py
Labels: bug, enhancement

#326 Add prettier to our stack
  .gitignore
  CHANGELOG.md
  package.json
  requirements_test.txt
  scripts/run-in-env.sh
  scripts/setup.sh
  scripts/setup_test.sh
  scripts/tests_and_coverage.sh
Labels: enhancement, dependencies

#334 Housekeeping user data Readme
  userdata/README.md
Labels: documentation
