Repository plugwise/python-plugwise, pull requests merged in 2023-07, with the labels that each got.

#345 Correct Adam_jip userdate: fix use of non-unique device names
  CHANGELOG.md
  fixtures/adam_jip/all_data.json
  tests/test_smile.py
  userdata/adam_jip/core.appliances.xml
  userdata/adam_jip/core.domain_objects.xml
Labels: bug

#346 Add domestic_hot_water_setpoint data to anna_heatpump_heating userdata, update relevant test-cases
  CHANGELOG.md
  fixtures/anna_heatpump_heating/all_data.json
  fixtures/m_anna_heatpump_cooling/all_data.json
  fixtures/m_anna_heatpump_idle/all_data.json
  tests/test_smile.py
  userdata/anna_heatpump_heating/core.appliances.xml
Labels: enhancement

#348 Release drafter
  .github/release.yml
Labels: documentation, enhancement

#347 Enhancement based on #425
  CHANGELOG.md
  plugwise/__init__.py
  tests/test_smile.py
Labels: enhancement

#355 Update build system requirements
  pyproject.toml
Labels: enhancement, dependencies

#359 Typing suggestions
  CHANGELOG.md
  package.json
  plugwise/constants.py
  pyproject.toml
Labels: enhancement, python

#362 Improvement: add Types for Number and Select
  CHANGELOG.md
  fixtures/adam_heatpump_cooling/all_data.json
  fixtures/adam_jip/all_data.json
  fixtures/adam_multiple_devices_per_zone/all_data.json
  fixtures/adam_onoff_cooling_fake_firmware/all_data.json
  fixtures/adam_plus_anna/all_data.json
  fixtures/adam_plus_anna_copy_with_error_domain_added/all_data.json
  fixtures/adam_plus_anna_new/all_data.json
  fixtures/adam_zone_per_device/all_data.json
  fixtures/anna_elga_2/all_data.json
  fixtures/anna_elga_2_cooling/all_data.json
  fixtures/anna_elga_2_schedule_off/all_data.json
  fixtures/anna_heatpump_cooling/all_data.json
  fixtures/anna_heatpump_cooling_fake_firmware/all_data.json
  fixtures/anna_heatpump_heating/all_data.json
  fixtures/anna_loria_cooling_active/all_data.json
  fixtures/anna_loria_heating_idle/all_data.json
  fixtures/anna_v4/all_data.json
  fixtures/anna_v4_dhw/all_data.json
  fixtures/anna_v4_no_tag/all_data.json
  fixtures/anna_without_boiler_fw3/all_data.json
  fixtures/anna_without_boiler_fw4/all_data.json
  fixtures/anna_without_boiler_fw42/all_data.json
  fixtures/legacy_anna/all_data.json
  fixtures/legacy_anna_2/all_data.json
  fixtures/m_adam_cooling/all_data.json
  fixtures/m_adam_heating/all_data.json
  fixtures/m_anna_heatpump_cooling/all_data.json
  fixtures/m_anna_heatpump_idle/all_data.json
  plugwise/__init__.py
  plugwise/constants.py
  plugwise/helper.py
  pyproject.toml
  scripts/update_fixtures.sh
  tests/test_smile.py
Labels: enhancement, python, quality
