Repository plugwise/python-plugwise, pull requests merged in 2023-04, with the labels that each got.

#290 Fix black and buildqueue-issues
  .github/workflows/verify.yml
  requirements_commit.txt
Labels: bug, dependencies

#292 Pause dependabot while starting renovatebot
  .github/dependabot.yml
Labels: dependencies

#293 Add labels
  renovate.json
Labels: enhancement, dependencies

#295 Smile(/stretch) initial
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/verify.yml
  CHANGELOG.md
  CODEOWNERS
  README.md
  plugwise/DEPENDENCIES.md
  plugwise/__init__.py
  plugwise/constants.py
  plugwise/exceptions.py
  plugwise/helper.py
  plugwise/smile/__init__.py
  plugwise/stick/__init__.py
  plugwise/stick/connections/__init__.py
  plugwise/stick/connections/serial.py
  plugwise/stick/connections/socket.py
  plugwise/stick/constants.py
  plugwise/stick/controller.py
  plugwise/stick/exceptions.py
  plugwise/stick/messages/__init__.py
  plugwise/stick/messages/requests.py
  plugwise/stick/messages/responses.py
  plugwise/stick/nodes/__init__.py
  plugwise/stick/nodes/circle.py
  plugwise/stick/nodes/circle_plus.py
  plugwise/stick/nodes/scan.py
  plugwise/stick/nodes/sed.py
  plugwise/stick/nodes/sense.py
  plugwise/stick/nodes/stealth.py
  plugwise/stick/nodes/switch.py
  plugwise/stick/parser.py
  plugwise/stick/util.py
  plugwise/util.py
  pyproject.toml
  scripts/complexity.sh
  tests/README.md
  tests/test_smile.py
  tests/test_stick.py
Labels: enhancement, dependencies

#296 Enable pre-commit, detect requirements better
  renovate.json
Labels: enhancement, dependencies

#303 Improve CI/CD
  .github/renovate.json
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  renovate.json
Labels: enhancement, dependencies

#304 Add system-xml data for legacy Anna and adapt
  CHANGELOG.md
  plugwise/__init__.py
  pyproject.toml
  tests/test_smile.py
  userdata/legacy_anna/system.xml
  userdata/legacy_anna/system_status_xml.xml
  userdata/legacy_anna_2/system_status_xml.xml
Labels: enhancement

#305 Retry fixing #231
  .gitignore
  CHANGELOG.md
  plugwise/__init__.py
  plugwise/constants.py
  plugwise/helper.py
  pyproject.toml
  tests/test_smile.py
Labels: enhancement, smile, quality

#306 Fix link to plugwise_usb-beta (underscore vs dash)
  README.md
Labels: documentation, enhancement
