Repository plugwise/python-plugwise, pull requests merged in 2023-03, with the labels that each got.

#276 Add (and default to) py311
  .github/workflows/merge.yml
  .github/workflows/verify.yml
  .pre-commit-config.yaml
  CHANGELOG.md
Labels: dependencies

#275 Fix USB communication queue handling
  CHANGELOG.md
  plugwise/controller.py
  plugwise/nodes/__init__.py
  pyproject.toml
Labels: bug, enhancement, usb

#279 Replace flake8 with ruff
  .flake8
  .pre-commit-config.yaml
  CHANGELOG.md
  plugwise/__init__.py
  plugwise/helper.py
  plugwise/smile.py
  pyproject.toml
  requirements_commit.txt
  scripts/tests_and_coverage.sh
  tests/test_smile.py
Labels: enhancement, dependencies
