Repository plugwise/python-plugwise, pull requests merged in 2024-06, with the labels that each got.

#571 Update README.md
  README.md
Labels: documentation

#565 Add a reboot_gateway() funtion for actual Plugwise devices.
  CHANGELOG.md
  fixtures/adam_heatpump_cooling/all_data.json
  fixtures/adam_jip/all_data.json
  fixtures/adam_multiple_devices_per_zone/all_data.json
  fixtures/adam_onoff_cooling_fake_firmware/all_data.json
  fixtures/adam_plus_anna/all_data.json
  fixtures/adam_plus_anna_new/all_data.json
  fixtures/adam_zone_per_device/all_data.json
  fixtures/anna_elga_2/all_data.json
  fixtures/anna_elga_2_cooling/all_data.json
  fixtures/anna_elga_2_schedule_off/all_data.json
  fixtures/anna_elga_no_cooling/all_data.json
  fixtures/anna_heatpump_cooling/all_data.json
  fixtures/anna_heatpump_cooling_fake_firmware/all_data.json
  fixtures/anna_heatpump_heating/all_data.json
  fixtures/anna_loria_cooling_active/all_data.json
  fixtures/anna_loria_driessens/all_data.json
  fixtures/anna_loria_heating_idle/all_data.json
  fixtures/anna_v4/all_data.json
  fixtures/anna_v4_dhw/all_data.json
  fixtures/anna_v4_no_tag/all_data.json
  fixtures/anna_without_boiler_fw441/all_data.json
  fixtures/m_adam_cooling/all_data.json
  fixtures/m_adam_heating/all_data.json
  fixtures/m_adam_jip/all_data.json
  fixtures/m_adam_multiple_devices_per_zone/all_data.json
  fixtures/m_anna_heatpump_cooling/all_data.json
  fixtures/m_anna_heatpump_idle/all_data.json
  fixtures/p1v4/all_data.json
  fixtures/p1v4_442_single/all_data.json
  fixtures/p1v4_442_triple/all_data.json
  plugwise/__init__.py
  plugwise/constants.py
  plugwise/data.py
  plugwise/exceptions.py
  plugwise/helper.py
  plugwise/legacy/smile.py
  plugwise/smile.py
  pyproject.toml
  tests/test_adam.py
  tests/test_init.py
  userdata/error/adam_plus_anna_new/core.domain_objects.xml
  userdata/reboot/adam_plus_anna_new/core.domain_objects.xml
Labels: enhancement

#581 Implement fix for Core Issue #119686
  CHANGELOG.md
  plugwise/smile.py
  pyproject.toml
  tests/test_init.py
Labels: bug
